name: driver_customer_app
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  mvc_pattern: ^8.11.0
  adaptive_theme: ^3.1.1
  global_configuration: ^2.0.0-nullsafety.1
  flutter_secure_storage: ^5.0.2
  fluttertoast: ^8.0.8
  font_awesome_flutter: ^10.1.0
  awesome_notifications: ^0.6.21
  cupertino_icons: ^1.0.2
  flutter_html: ^3.0.0-alpha.5
  auto_size_text: ^3.0.0
  brasil_fields: 1.4.2
  firebase_messaging: ^14.1.2
  firebase_core: ^2.3.0
  firebase_analytics: ^10.0.6
  url_launcher: ^6.0.20
  sign_button: ^2.0.2
  google_sign_in: ^5.4.0
  validators: ^3.0.0
  google_place: ^0.4.7
  flutter_typeahead: ^4.0.0
  cached_network_image: ^3.2.1
  select_dialog: ^2.0.0
  image_picker: ^0.8.5+3
  permission_handler: ^10.0.0
  loader_overlay: ^2.0.7
  timeline_tile: ^2.0.0
  flutter_switch: ^0.3.2
  flutter_stripe: ^4.0.0
  webview_flutter: ^3.0.4
  flutter_launcher_icons: ^0.11.0
  change_app_package_name: ^1.1.0
  location: ^4.4.0
  google_maps_flutter: ^2.1.12
  place_picker: ^0.9.19
  avatar_glow: ^2.0.2
  bubble: ^1.2.1
  file_picker: ^5.2.0+1
  mime: ^1.0.2
  flutter_polyline_points: ^1.0.0
  intl_phone_field: ^3.1.0
  pin_code_text_field: ^1.8.0
  flutter_rating_bar: ^4.0.1
  carousel_slider: ^4.2.1
  flutter_svg: ^1.1.6
  lottie: ^2.2.0
  flutter_advanced_drawer: ^1.3.3
  flutter_toggle_tab: ^1.2.0
  flutter_datetime_picker: ^1.5.1
  bottom_picker: ^2.0.1

  flutter_localizations:
    sdk: flutter
  maps_launcher: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  android: true
  ios: true
  image_path: "assets/img/eb669a40-feb6-47af-b97d-3e6571162c41.JPG"
  remove_alpha_ios: true
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:
  assets:
    - assets/cfg/
    - assets/img/

  generate: true

  uses-material-design: true

  fonts:
   - family: CM Sans Serif
     fonts:
       - asset: assets/fonts/cm_sans_serif_2012.ttf
   - family: Uber
     fonts:
       - asset: assets/fonts/ClanOT-Medium.ttf
       - asset: assets/fonts/ClanOT-Bold.ttf
         weight: 700