// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC7IEfTxr_7EJ9I-e7W_jY-g37GRKp3xpA',
    appId: '1:771996260275:android:3d7742c0a7dd3bf11f9dc6',
    messagingSenderId: '771996260275',
    projectId: 'ts-drivers',
    storageBucket: 'ts-drivers.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDuOohh83t9eNrXV2VbWiltjGz4M2rA52E',
    appId: '1:771996260275:ios:dbcd60f8e986f5c21f9dc6',
    messagingSenderId: '771996260275',
    projectId: 'ts-drivers',
    storageBucket: 'ts-drivers.appspot.com',
    androidClientId: '771996260275-5rkpd87mguna28rm79gj0g91jhmqa37u.apps.googleusercontent.com',
    iosClientId: '771996260275-34iiosrohs57nkl1aguak25cibhjstr0.apps.googleusercontent.com',
    iosBundleId: 'io.skttech.user',
  );
}
